name       : python-backcall
version    : 0.2.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/a2/40/764a663805d84deee23043e1426a9175567db89c8b3287b5c2ad9f71aa93/backcall-0.2.0.tar.gz : 5cbdbf27be5e7cfadb448baf0aa95508f91f2bbc6c6437cd9cd06e2a4c215e1e
homepage   : https://github.com/takluyver/backcall
license    : BSD-3-Clause
component  : programming.python
summary    : Backwards compatible callback APIs
description: |
    Specifications for callback functions passed in to an API
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
